- name: Install redis component
  hosts: redis
  become: yes
  tasks:
  - name: Installing redis rpm packages
    ansible.builtin.yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
      state: installed

  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: out #output is variable name
    ignore_errors: true

  - when: out.rc != 0
    name: create user roboshop
    #become: yes # we need sudo access for this task only
    ansible.builtin.user:
      name: roboshop

  - name: start and enable redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes
  
  - name: enable remote connections to redis
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  
  - name: restart redis
    ansible.builtin.service:
      name: redis
      state: restarted    